import { Hospital, Bed } from '../types/hospital';
import { Ambulance } from '../types/ambulance';
import { SymptomOption } from '../types/prioritization';
import { QueuePatient } from '../types/queue';
import { HospitalPreAlert } from '../types/preAlert';

export const INITIAL_SYMPTOMS: SymptomOption[] = [
  {
    id: 'chest_pain',
    label: 'Severe Chest Pain / Pressure',
    category: 'cardiovascular',
    baselineSeverity: 'CRITICAL',
    iconName: 'HeartPulse',
    commonCombinations: ['difficulty_breathing', 'sweating', 'dizziness'],
    requiredFacilities: { emergencyDepartment: true, icu: true, cardiacCare: true, oxygenSupport: true }
  },
  {
    id: 'difficulty_breathing',
    label: 'Severe Difficulty Breathing / Shortness of Breath',
    category: 'respiratory',
    baselineSeverity: 'CRITICAL',
    iconName: 'Wind',
    commonCombinations: ['chest_pain', 'cough', 'cyanosis'],
    requiredFacilities: { emergencyDepartment: true, icu: true, oxygenSupport: true, ventilator: true }
  },
  {
    id: 'unconsciousness',
    label: 'Unconsciousness / Fainting / Altered Mental State',
    category: 'neurological',
    baselineSeverity: 'CRITICAL',
    iconName: 'Activity',
    commonCombinations: ['head_injury', 'seizure'],
    requiredFacilities: { emergencyDepartment: true, icu: true, oxygenSupport: true, ventilator: true }
  },
  {
    id: 'severe_bleeding',
    label: 'Severe Uncontrolled Bleeding',
    category: 'trauma',
    baselineSeverity: 'CRITICAL',
    iconName: 'Droplets',
    commonCombinations: ['fracture_injury', 'dizziness'],
    requiredFacilities: { emergencyDepartment: true, traumaCare: true, icu: true }
  },
  {
    id: 'stroke_symptoms',
    label: 'Facial Droop / Arm Weakness / Slurred Speech (FAST)',
    category: 'neurological',
    baselineSeverity: 'CRITICAL',
    iconName: 'Brain',
    commonCombinations: ['confusion', 'headache'],
    requiredFacilities: { emergencyDepartment: true, strokeUnit: true, icu: true }
  },
  {
    id: 'head_injury',
    label: 'Head Injury / Traumatic Concussion',
    category: 'trauma',
    baselineSeverity: 'HIGH',
    iconName: 'ShieldAlert',
    commonCombinations: ['unconsciousness', 'vomiting'],
    requiredFacilities: { emergencyDepartment: true, traumaCare: true, icu: true }
  },
  {
    id: 'fracture_injury',
    label: 'Severe Fracture / Deformity / Major Trauma',
    category: 'trauma',
    baselineSeverity: 'HIGH',
    iconName: 'Bone',
    commonCombinations: ['severe_pain', 'swelling'],
    requiredFacilities: { emergencyDepartment: true, orthopedicSurgeon: true, traumaCare: true }
  },
  {
    id: 'severe_abdominal_pain',
    label: 'Acute Severe Abdominal Pain',
    category: 'gastrointestinal',
    baselineSeverity: 'HIGH',
    iconName: 'AlertCircle',
    commonCombinations: ['high_fever', 'vomiting'],
    requiredFacilities: { emergencyDepartment: true }
  },
  {
    id: 'high_fever',
    label: 'High Fever (> 103°F / 39.4°C) with Chills',
    category: 'general',
    baselineSeverity: 'MODERATE',
    iconName: 'Thermometer',
    commonCombinations: ['cough', 'body_pain'],
    requiredFacilities: { emergencyDepartment: true }
  },
  {
    id: 'moderate_burn',
    label: 'Thermal Burn / Scald Injury',
    category: 'trauma',
    baselineSeverity: 'MODERATE',
    iconName: 'Flame',
    commonCombinations: ['pain', 'blisters'],
    requiredFacilities: { emergencyDepartment: true, traumaCare: true }
  },
  {
    id: 'persistent_vomiting',
    label: 'Persistent Vomiting / Dehydration',
    category: 'gastrointestinal',
    baselineSeverity: 'MODERATE',
    iconName: 'HelpCircle',
    commonCombinations: ['abdominal_pain', 'fever'],
    requiredFacilities: { emergencyDepartment: true }
  },
  {
    id: 'minor_sprain',
    label: 'Minor Sprain / Cut / Mild Bruising',
    category: 'general',
    baselineSeverity: 'LOW',
    iconName: 'Bandage',
    commonCombinations: ['mild_pain'],
    requiredFacilities: { emergencyDepartment: false }
  },
  {
    id: 'mild_cough_cold',
    label: 'Mild Cough, Cold or Sore Throat',
    category: 'respiratory',
    baselineSeverity: 'LOW',
    iconName: 'Smile',
    commonCombinations: ['sneezing'],
    requiredFacilities: { emergencyDepartment: false }
  }
];

export const INITIAL_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-citycare',
    name: 'CityCare Medical Center',
    type: 'Super Specialty',
    address: '84 Metro Health Blvd, Central District',
    distanceKm: 3.2,
    travelTimeMinutes: 8,
    trafficCondition: 'Low',
    coordinates: { lat: 12.9716, lng: 77.5946 },
    phone: '+91 80 4120 5500',
    isOpen: true,
    totalBeds: 220,
    availableBeds: 42,
    totalICUBeds: 24,
    availableICUBeds: 5,
    totalEmergencyBeds: 35,
    availableEmergencyBeds: 9,
    currentERLoadPercent: 42,
    estimatedWaitTimeMinutes: 8,
    emergencyAvailable: true,
    icuAvailable: true,
    oxygenSupport: true,
    ventilatorAvailability: true,
    traumaLevel: 1,
    cardiacCareAvailable: true,
    strokeUnitAvailable: true,
    orthopedicAvailable: true,
    pediatricAvailable: true,
    ambulanceAvailableCount: 3,
    rating: 4.8,
    specialties: ['Cardiology', 'Emergency Medicine', 'Neurology', 'Pulmonology', 'Trauma Surgery']
  },
  {
    id: 'hosp-metro-trauma',
    name: 'Metro Trauma & Apex Institute',
    type: 'Trauma Center Level 1',
    address: '12 Expressway Junction, North Ring Rd',
    distanceKm: 2.1,
    travelTimeMinutes: 22, // Heavy traffic
    trafficCondition: 'Heavy',
    coordinates: { lat: 12.9850, lng: 77.6050 },
    phone: '+91 80 2299 8800',
    isOpen: true,
    totalBeds: 310,
    availableBeds: 18,
    totalICUBeds: 30,
    availableICUBeds: 0, // NO ICU currently
    totalEmergencyBeds: 45,
    availableEmergencyBeds: 2,
    currentERLoadPercent: 94,
    estimatedWaitTimeMinutes: 38,
    emergencyAvailable: true,
    icuAvailable: false, // Currently saturated
    oxygenSupport: true,
    ventilatorAvailability: true,
    traumaLevel: 1,
    cardiacCareAvailable: true,
    strokeUnitAvailable: true,
    orthopedicAvailable: true,
    pediatricAvailable: false,
    ambulanceAvailableCount: 1,
    rating: 4.6,
    specialties: ['Trauma & Orthopedics', 'Neurosurgery', 'Critical Care', 'Burn Unit']
  },
  {
    id: 'hosp-lifeline',
    name: 'LifeLine Super Specialty Hospital',
    type: 'Super Specialty',
    address: '405 Tech Park East Corridor',
    distanceKm: 5.4,
    travelTimeMinutes: 12,
    trafficCondition: 'Low',
    coordinates: { lat: 12.9560, lng: 77.6250 },
    phone: '+91 80 6700 1122',
    isOpen: true,
    totalBeds: 180,
    availableBeds: 36,
    totalICUBeds: 18,
    availableICUBeds: 4,
    totalEmergencyBeds: 25,
    availableEmergencyBeds: 7,
    currentERLoadPercent: 48,
    estimatedWaitTimeMinutes: 11,
    emergencyAvailable: true,
    icuAvailable: true,
    oxygenSupport: true,
    ventilatorAvailability: true,
    traumaLevel: 2,
    cardiacCareAvailable: true,
    strokeUnitAvailable: true,
    orthopedicAvailable: true,
    pediatricAvailable: true,
    ambulanceAvailableCount: 2,
    rating: 4.7,
    specialties: ['Cardiac Sciences', 'Neurology', 'Internal Medicine', 'Pediatrics']
  },
  {
    id: 'hosp-st-jude',
    name: 'St. Jude Memorial Hospital',
    type: 'General Hospital',
    address: '19 Heritage Road, West Extension',
    distanceKm: 4.8,
    travelTimeMinutes: 14,
    trafficCondition: 'Moderate',
    coordinates: { lat: 12.9420, lng: 77.5800 },
    phone: '+91 80 2555 4321',
    isOpen: true,
    totalBeds: 140,
    availableBeds: 28,
    totalICUBeds: 12,
    availableICUBeds: 2,
    totalEmergencyBeds: 20,
    availableEmergencyBeds: 5,
    currentERLoadPercent: 62,
    estimatedWaitTimeMinutes: 16,
    emergencyAvailable: true,
    icuAvailable: true,
    oxygenSupport: true,
    ventilatorAvailability: true,
    traumaLevel: 2,
    cardiacCareAvailable: false,
    strokeUnitAvailable: false,
    orthopedicAvailable: true,
    pediatricAvailable: true,
    ambulanceAvailableCount: 2,
    rating: 4.5,
    specialties: ['General Surgery', 'Obstetrics', 'Orthopedics', 'General Emergency']
  },
  {
    id: 'hosp-apollo-apex',
    name: 'Apex Heart & Vascular Institute',
    type: 'Cardiac Center',
    address: '100 South Boulevard, Medical Square',
    distanceKm: 6.2,
    travelTimeMinutes: 15,
    trafficCondition: 'Low',
    coordinates: { lat: 12.9250, lng: 77.5920 },
    phone: '+91 80 4999 0000',
    isOpen: true,
    totalBeds: 160,
    availableBeds: 30,
    totalICUBeds: 20,
    availableICUBeds: 6,
    totalEmergencyBeds: 22,
    availableEmergencyBeds: 6,
    currentERLoadPercent: 51,
    estimatedWaitTimeMinutes: 10,
    emergencyAvailable: true,
    icuAvailable: true,
    oxygenSupport: true,
    ventilatorAvailability: true,
    traumaLevel: 2,
    cardiacCareAvailable: true,
    strokeUnitAvailable: true,
    orthopedicAvailable: false,
    pediatricAvailable: false,
    ambulanceAvailableCount: 3,
    rating: 4.9,
    specialties: ['Interventional Cardiology', 'Cardiothoracic Surgery', 'Vascular Care', 'CCU']
  },
  {
    id: 'hosp-community-west',
    name: 'Westside Community Hospital',
    type: 'Community Hospital',
    address: '56 Green Avenue, West Park',
    distanceKm: 7.0,
    travelTimeMinutes: 18,
    trafficCondition: 'Moderate',
    coordinates: { lat: 12.9600, lng: 77.5450 },
    phone: '+91 80 2341 9090',
    isOpen: true,
    totalBeds: 90,
    availableBeds: 22,
    totalICUBeds: 6,
    availableICUBeds: 1,
    totalEmergencyBeds: 14,
    availableEmergencyBeds: 4,
    currentERLoadPercent: 71,
    estimatedWaitTimeMinutes: 20,
    emergencyAvailable: true,
    icuAvailable: true,
    oxygenSupport: true,
    ventilatorAvailability: false,
    traumaLevel: 3,
    cardiacCareAvailable: false,
    strokeUnitAvailable: false,
    orthopedicAvailable: true,
    pediatricAvailable: true,
    ambulanceAvailableCount: 1,
    rating: 4.2,
    specialties: ['Family Medicine', 'Basic Emergency', 'Pediatrics', 'Minor Trauma']
  }
];

export const INITIAL_AMBULANCES: Ambulance[] = [
  {
    id: 'amb-1',
    vehicleNumber: 'KA-01-A17',
    driverName: 'Rajesh Kumar',
    driverPhone: '+91 98450 12345',
    paramedicName: 'Ananya Sharma (EMT-P)',
    status: 'Available',
    currentLocation: {
      lat: 12.9680,
      lng: 77.5900,
      address: 'Central Station Standby Bay 2'
    },
    etaMinutes: 6,
    oxygenSupport: true,
    ventilatorSupport: true,
    defibrillator: true,
    advancedLifeSupport: true,
    traumaKit: true
  },
  {
    id: 'amb-2',
    vehicleNumber: 'KA-01-A22',
    driverName: 'Vikram Singh',
    driverPhone: '+91 98450 67890',
    paramedicName: 'David Paul (EMT-B)',
    status: 'Available',
    currentLocation: {
      lat: 12.9550,
      lng: 77.6100,
      address: 'Indiranagar Hub Standby'
    },
    etaMinutes: 9,
    oxygenSupport: true,
    ventilatorSupport: false,
    defibrillator: true,
    advancedLifeSupport: false,
    traumaKit: true
  },
  {
    id: 'amb-3',
    vehicleNumber: 'KA-01-A09',
    driverName: 'Farhan Akhtar',
    driverPhone: '+91 98450 33445',
    paramedicName: 'Pooja Reddy (EMT-P)',
    status: 'En Route',
    currentLocation: {
      lat: 12.9810,
      lng: 77.6020,
      address: 'En route to Metro Trauma'
    },
    destinationHospitalId: 'hosp-metro-trauma',
    destinationHospitalName: 'Metro Trauma & Apex Institute',
    assignedPatientId: 'P-1039',
    assignedPatientName: 'Suresh Menon',
    patientSeverity: 'HIGH',
    etaMinutes: 14,
    oxygenSupport: true,
    ventilatorSupport: true,
    defibrillator: true,
    advancedLifeSupport: true,
    traumaKit: true
  },
  {
    id: 'amb-4',
    vehicleNumber: 'KA-01-A35',
    driverName: 'Suresh Patil',
    driverPhone: '+91 98450 88991',
    paramedicName: 'Sneha Patel (EMT-P)',
    status: 'Available',
    currentLocation: {
      lat: 12.9300,
      lng: 77.5850,
      address: 'Jayanagar Emergency Standby'
    },
    etaMinutes: 11,
    oxygenSupport: true,
    ventilatorSupport: true,
    defibrillator: true,
    advancedLifeSupport: true,
    traumaKit: true
  },
  {
    id: 'amb-5',
    vehicleNumber: 'KA-01-A44',
    driverName: 'Manoj Hegde',
    driverPhone: '+91 98450 55667',
    paramedicName: 'Ramesh Naik (EMT-B)',
    status: 'At Hospital',
    currentLocation: {
      lat: 12.9716,
      lng: 77.5946,
      address: 'CityCare ER Bay 1'
    },
    destinationHospitalId: 'hosp-citycare',
    destinationHospitalName: 'CityCare Medical Center',
    etaMinutes: 0,
    oxygenSupport: true,
    ventilatorSupport: false,
    defibrillator: true,
    advancedLifeSupport: false,
    traumaKit: true
  }
];

export const INITIAL_BEDS: Bed[] = [
  // CityCare ER & ICU Beds
  { id: 'b-er-101', hospitalId: 'hosp-citycare', bedNumber: 'ER-01', wardType: 'Emergency', status: 'Occupied', patientId: 'P-1021', patientName: 'Arun V.', severity: 'CRITICAL', assignedDoctor: 'Dr. Priya Rao', updatedAt: '10 min ago' },
  { id: 'b-er-102', hospitalId: 'hosp-citycare', bedNumber: 'ER-02', wardType: 'Emergency', status: 'Occupied', patientId: 'P-1025', patientName: 'Kiran B.', severity: 'HIGH', assignedDoctor: 'Dr. Priya Rao', updatedAt: '25 min ago' },
  { id: 'b-er-103', hospitalId: 'hosp-citycare', bedNumber: 'ER-03', wardType: 'Emergency', status: 'Available', updatedAt: 'Just now' },
  { id: 'b-er-104', hospitalId: 'hosp-citycare', bedNumber: 'ER-04', wardType: 'Emergency', status: 'Available', updatedAt: 'Just now' },
  { id: 'b-er-105', hospitalId: 'hosp-citycare', bedNumber: 'ER-05', wardType: 'Emergency', status: 'Cleaning', updatedAt: '5 min ago' },
  { id: 'b-er-106', hospitalId: 'hosp-citycare', bedNumber: 'ER-06', wardType: 'Emergency', status: 'Available', updatedAt: 'Just now' },
  { id: 'b-er-107', hospitalId: 'hosp-citycare', bedNumber: 'ER-07', wardType: 'Emergency', status: 'Available', updatedAt: 'Just now' },
  { id: 'b-er-108', hospitalId: 'hosp-citycare', bedNumber: 'ER-08', wardType: 'Emergency', status: 'Occupied', patientId: 'P-1030', patientName: 'Meena S.', severity: 'MODERATE', assignedDoctor: 'Dr. Rohit Sen', updatedAt: '1 hour ago' },
  
  // CityCare ICU Beds
  { id: 'b-icu-201', hospitalId: 'hosp-citycare', bedNumber: 'ICU-01', wardType: 'ICU', status: 'Occupied', patientId: 'P-1008', patientName: 'Devdas R.', severity: 'CRITICAL', assignedDoctor: 'Dr. Sunita Kulkarni', updatedAt: '3 hours ago' },
  { id: 'b-icu-202', hospitalId: 'hosp-citycare', bedNumber: 'ICU-02', wardType: 'ICU', status: 'Occupied', patientId: 'P-1014', patientName: 'Gita M.', severity: 'CRITICAL', assignedDoctor: 'Dr. Sunita Kulkarni', updatedAt: '5 hours ago' },
  { id: 'b-icu-203', hospitalId: 'hosp-citycare', bedNumber: 'ICU-03', wardType: 'ICU', status: 'Available', updatedAt: 'Just now' },
  { id: 'b-icu-204', hospitalId: 'hosp-citycare', bedNumber: 'ICU-04', wardType: 'ICU', status: 'Available', updatedAt: 'Just now' },
  { id: 'b-icu-205', hospitalId: 'hosp-citycare', bedNumber: 'ICU-05', wardType: 'ICU', status: 'Available', updatedAt: 'Just now' },
  { id: 'b-icu-206', hospitalId: 'hosp-citycare', bedNumber: 'ICU-06', wardType: 'ICU', status: 'Reserved', patientName: 'Reserved for Incoming Pre-Alert', severity: 'CRITICAL', updatedAt: '2 min ago' }
];

export const INITIAL_QUEUE_PATIENTS: QueuePatient[] = [
  {
    id: 'q-1',
    tokenNumber: '#A098',
    patientName: 'Ramanathan G.',
    age: 62,
    gender: 'male',
    severity: 'CRITICAL',
    symptoms: ['Acute Chest Pain', 'Diaphoresis'],
    arrivalTime: new Date(Date.now() - 35 * 60000).toISOString(),
    estimatedWaitMinutes: 0,
    status: 'Treatment',
    assignedDoctor: 'Dr. Priya Rao',
    assignedRoom: 'Resus Bay 1',
    hospitalId: 'hosp-citycare',
    queuePosition: 0
  },
  {
    id: 'q-2',
    tokenNumber: '#A099',
    patientName: 'Deepa Verma',
    age: 34,
    gender: 'female',
    severity: 'HIGH',
    symptoms: ['Compound Wrist Fracture', 'Severe Pain'],
    arrivalTime: new Date(Date.now() - 25 * 60000).toISOString(),
    estimatedWaitMinutes: 2,
    status: 'Under Assessment',
    assignedDoctor: 'Dr. Rohit Sen',
    assignedRoom: 'ER Room 3',
    hospitalId: 'hosp-citycare',
    queuePosition: 0
  },
  {
    id: 'q-3',
    tokenNumber: '#A100',
    patientName: 'Amitava Bose',
    age: 51,
    gender: 'male',
    severity: 'HIGH',
    symptoms: ['Acute Abdominal Pain', 'Vomiting'],
    arrivalTime: new Date(Date.now() - 18 * 60000).toISOString(),
    estimatedWaitMinutes: 5,
    status: 'Waiting',
    hospitalId: 'hosp-citycare',
    queuePosition: 1
  },
  {
    id: 'q-4',
    tokenNumber: '#A101',
    patientName: 'Shalini Nair',
    age: 28,
    gender: 'female',
    severity: 'MODERATE',
    symptoms: ['High Fever (103.5°F)', 'Dehydration'],
    arrivalTime: new Date(Date.now() - 14 * 60000).toISOString(),
    estimatedWaitMinutes: 8,
    status: 'Waiting',
    hospitalId: 'hosp-citycare',
    queuePosition: 2
  },
  {
    id: 'q-5',
    tokenNumber: '#A102',
    patientName: 'Harish Chandra',
    age: 45,
    gender: 'male',
    severity: 'MODERATE',
    symptoms: ['Laceration on Left Forearm', 'Bleeding Controlled'],
    arrivalTime: new Date(Date.now() - 10 * 60000).toISOString(),
    estimatedWaitMinutes: 12,
    status: 'Waiting',
    hospitalId: 'hosp-citycare',
    queuePosition: 3
  },
  {
    id: 'q-6',
    tokenNumber: '#A103',
    patientName: 'Lavanya M.',
    age: 22,
    gender: 'female',
    severity: 'LOW',
    symptoms: ['Mild Ankle Sprain'],
    arrivalTime: new Date(Date.now() - 5 * 60000).toISOString(),
    estimatedWaitMinutes: 18,
    status: 'Waiting',
    hospitalId: 'hosp-citycare',
    queuePosition: 4
  }
];

export const INITIAL_PRE_ALERTS: HospitalPreAlert[] = [
  {
    id: 'PA-1038',
    patientId: 'P-1038',
    patientName: 'Tanvi Joshi',
    age: 55,
    gender: 'female',
    severity: 'HIGH',
    symptoms: ['Suspected TIA / Transient Slurred Speech'],
    vitalsSummary: 'BP: 165/95 | HR: 88 | SpO2: 97%',
    etaMinutes: 7,
    requiredFacilities: {
      emergencyDepartment: true,
      icu: true,
      oxygenSupport: true,
      ventilator: false,
      traumaCare: false,
      cardiacCare: false,
      strokeUnit: true,
      orthopedicSurgeon: false,
      pediatricEmergency: false
    },
    ambulanceId: 'amb-1',
    ambulanceVehicleNumber: 'KA-01-A17',
    originLocation: 'Koramangala 4th Block',
    destinationHospitalId: 'hosp-citycare',
    destinationHospitalName: 'CityCare Medical Center',
    status: 'Resources Preparing',
    createdAt: new Date(Date.now() - 8 * 60000).toISOString(),
    preparation: {
      alertReceived: true,
      icuReserved: true,
      emergencyRoomAssigned: true,
      assignedRoomNumber: 'Stroke Bay 2',
      doctorNotified: true,
      assignedDoctorName: 'Dr. Priya Rao (Emergency Physician)',
      bloodBankAlerted: true,
      readyForArrival: true
    }
  }
];
