"""initial schema

Revision ID: 3c284fd76226
Revises: 
Create Date: 2026-09-04 23:30:03.327794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c284fd76226'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('emergency_available', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'UNDER_REVIEW', name='hospital_status', native_enum=False), server_default='ACTIVE', nullable=False),
    sa.Column('geoapify_place_id', sa.String(length=255), nullable=True),
    sa.Column('locationiq_place_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_hospitals_city'), 'hospitals', ['city'], unique=False)
    op.create_index('ix_hospitals_coords', 'hospitals', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('PATIENT', 'HOSPITAL_STAFF', 'ADMIN', name='user_role', native_enum=False), server_default='PATIENT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ambulances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_number', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('BLS', 'ALS', 'MORTUARY', name='ambulance_type', native_enum=False), server_default='ALS', nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'DISPATCHED', 'EN_ROUTE', 'AT_HOSPITAL', 'MAINTENANCE', name='ambulance_status', native_enum=False), server_default='AVAILABLE', nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('current_assignment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_number')
    )
    op.create_index('ix_ambulances_coords', 'ambulances', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_ambulances_hospital_id'), 'ambulances', ['hospital_id'], unique=False)
    op.create_index('ix_ambulances_status', 'ambulances', ['status'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=128), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'BUSY', 'OFF_DUTY', name='doctor_status', native_enum=False), server_default='AVAILABLE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_doctors_hospital_id'), 'doctors', ['hospital_id'], unique=False)
    op.create_table('emergency_rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FULL', 'CLOSED', name='emergency_room_status', native_enum=False), server_default='OPEN', nullable=False),
    sa.Column('current_patients', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_rooms_hospital_id'), 'emergency_rooms', ['hospital_id'], unique=False)
    op.create_table('hospital_operations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('current_er_load', sa.Integer(), nullable=False),
    sa.Column('estimated_wait_minutes', sa.Integer(), nullable=False),
    sa.Column('available_ambulances', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', name='uq_hospital_operations_hospital')
    )
    op.create_table('hospital_staff',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('staff_role', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'hospital_id', name='uq_staff_user_hospital')
    )
    op.create_index(op.f('ix_hospital_staff_hospital_id'), 'hospital_staff', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_hospital_staff_user_id'), 'hospital_staff', ['user_id'], unique=False)
    op.create_table('icu_units',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('total_beds', sa.Integer(), nullable=False),
    sa.Column('available_beds', sa.Integer(), nullable=False),
    sa.Column('occupied_beds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icu_units_hospital_id'), 'icu_units', ['hospital_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('emergency_contact', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('room_number', sa.String(length=32), nullable=False),
    sa.Column('room_type', sa.String(length=64), nullable=False),
    sa.Column('floor', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE', name='room_status', native_enum=False), server_default='AVAILABLE', nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'room_number', name='uq_room_hospital_number')
    )
    op.create_index(op.f('ix_rooms_hospital_id'), 'rooms', ['hospital_id'], unique=False)
    op.create_table('beds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=True),
    sa.Column('bed_number', sa.String(length=32), nullable=False),
    sa.Column('bed_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'RESERVED', 'MAINTENANCE', name='bed_status', native_enum=False), server_default='AVAILABLE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'bed_number', name='uq_bed_hospital_number')
    )
    op.create_index(op.f('ix_beds_hospital_id'), 'beds', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_beds_room_id'), 'beds', ['room_id'], unique=False)
    op.create_index('ix_beds_status', 'beds', ['status'], unique=False)
    op.create_table('emergency_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('reported_symptoms', sa.Text(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MODERATE', 'LOW', name='severity_level', native_enum=False), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('REPORTED', 'DISPATCHED', 'EN_ROUTE', 'ARRIVED', 'TREATING', 'RESOLVED', 'CANCELLED', name='emergency_case_status', native_enum=False), server_default='REPORTED', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_emergency_cases_coords', 'emergency_cases', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_emergency_cases_patient_id'), 'emergency_cases', ['patient_id'], unique=False)
    op.create_index('ix_emergency_cases_severity', 'emergency_cases', ['severity'], unique=False)
    op.create_index('ix_emergency_cases_status', 'emergency_cases', ['status'], unique=False)
    op.create_table('queue_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('hospital_id', sa.String(length=36), nullable=False),
    sa.Column('emergency_case_id', sa.String(length=36), nullable=True),
    sa.Column('token_number', sa.String(length=32), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'CALLED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='queue_status', native_enum=False), server_default='WAITING', nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['emergency_case_id'], ['emergency_cases.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'token_number', name='uq_queue_token_hospital_number')
    )
    op.create_index(op.f('ix_queue_tokens_emergency_case_id'), 'queue_tokens', ['emergency_case_id'], unique=False)
    op.create_index(op.f('ix_queue_tokens_hospital_id'), 'queue_tokens', ['hospital_id'], unique=False)
    op.create_index('ix_queue_tokens_hospital_status', 'queue_tokens', ['hospital_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_queue_tokens_hospital_status', table_name='queue_tokens')
    op.drop_index(op.f('ix_queue_tokens_hospital_id'), table_name='queue_tokens')
    op.drop_index(op.f('ix_queue_tokens_emergency_case_id'), table_name='queue_tokens')
    op.drop_table('queue_tokens')
    op.drop_index('ix_emergency_cases_status', table_name='emergency_cases')
    op.drop_index('ix_emergency_cases_severity', table_name='emergency_cases')
    op.drop_index(op.f('ix_emergency_cases_patient_id'), table_name='emergency_cases')
    op.drop_index('ix_emergency_cases_coords', table_name='emergency_cases')
    op.drop_table('emergency_cases')
    op.drop_index('ix_beds_status', table_name='beds')
    op.drop_index(op.f('ix_beds_room_id'), table_name='beds')
    op.drop_index(op.f('ix_beds_hospital_id'), table_name='beds')
    op.drop_table('beds')
    op.drop_index(op.f('ix_rooms_hospital_id'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_icu_units_hospital_id'), table_name='icu_units')
    op.drop_table('icu_units')
    op.drop_index(op.f('ix_hospital_staff_user_id'), table_name='hospital_staff')
    op.drop_index(op.f('ix_hospital_staff_hospital_id'), table_name='hospital_staff')
    op.drop_table('hospital_staff')
    op.drop_table('hospital_operations')
    op.drop_index(op.f('ix_emergency_rooms_hospital_id'), table_name='emergency_rooms')
    op.drop_table('emergency_rooms')
    op.drop_index(op.f('ix_doctors_hospital_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index('ix_ambulances_status', table_name='ambulances')
    op.drop_index(op.f('ix_ambulances_hospital_id'), table_name='ambulances')
    op.drop_index('ix_ambulances_coords', table_name='ambulances')
    op.drop_table('ambulances')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index('ix_hospitals_coords', table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_city'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###